### ISSUE TITLE
[chrome] missing header color in light mode

### ISSUE THREAD

**Issue by MathieuDerelle** [chteuchteu/MaterialDesignIcons-Picker#104] opened 2023-04-05 09:21 UTC
![image](https://user-images.githubusercontent.com/16286023/230037948-26d46e35-03ed-4d64-ba3c-a85073a70258.png)

upon inspection, the CSS variable `--background-header` seems to be missing
![image](https://user-images.githubusercontent.com/16286023/230038133-868093e4-cc8d-4da1-896c-503d77d3b846.png)

extension version : 3.13.0

(still affected by that after uninstalling and re-installing)

**Comment by chteuchteu** [comment] 2023-04-07 11:45
@MathieuDerelle Thank you for this bug report! This issue is a duplicate of #103 
The issue has been fixed, but not yet deployed.

**Closed as completed by chteuchteu** 2023-04-07 11:45 UTC
Labels: bug
